#全域性配置,比如配置發件人
global:
  resolve_timeout: 5m    #處理超時時間，預設為5min
  smtp_smarthost: 'smtp.gmail.com:587'  # 郵箱smtp伺服器代理
  smtp_from: 'servergazer@n-warp.com' # 傳送郵箱名稱
  smtp_auth_username: 'servergazer@n-warp.com' # 郵箱名稱
  smtp_auth_password: '1qw23eR$'              # 郵箱密碼或授權碼

# 定義模板資訊,可以自定義html模板,發郵件的時候用自己定義的模板內容發
#templates:
#  - 'template/*.tmpl'

# 定義路由樹資訊,這個路由可以接收到所有的告警,還可以繼續配置路由,比如project: zhidaoAPP(prometheus 告警規則中自定義的lable)發給誰,project: baoxian的發給誰
route:
  group_by: ['alertname'] # 報警分組依據
  group_wait: 10s         # 最初即第一次等待多久時間傳送一組警報的通知
  # group_interval: 60s     # 在傳送新警報前的等待時間
  #  repeat_interval: 1h     # 傳送重複警報的週期 對於email配置中，此項不可以設定過低，否則將會由於郵件傳送太多頻繁，被smtp伺服器拒絕
  receiver: 'email'       # 傳送警報的接收者的名稱，以下receivers name的名稱

# 定義警報接收者資訊
receivers:
  - name: 'email'  # 路由中對應的receiver名稱
    email_configs: # 郵箱配置
    - to: 'nwarprd@4gamers.com.tw'   # 接收警報的email配置
#      #html: '{{ template "test.html" . }}'  # 設定郵箱的內容模板
