package com.example.kirby.prometheus;

public enum MeterRegistryName {
	TUNNEL_LATENCY, TUNNEL_LATENCY_THRESHOLD, ISP_SERVER_VPN_COUNT, ISP_SERVER_MONITOR, ISP_SERVER_PLAYER_COUNT,
	TUNNEL_BANDWITH, NWARP_MGR_APPENGINE_RSP, VERSION_FIRMWARE, VERSION_GAMELIST, VERSION_GAMEDETECTOR,
	MQTT_ONLINE_PLAYER
}
